services:
    postgres:
        image: postgres:latest
        container_name: plsync-postgres
        env_file: .env
        ports:
            - "5432:5432"
    astro:
        build: .
        env_file:
            - .env
        container_name: plsync-astro
        ports:
            - "4321:4321"
        depends_on:
            - postgres
